# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 17:27
from __future__ import unicode_literals

import beers.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('abv', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alcohol by volume')),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'Yellow'), (2, 'Amber'), (3, 'Brown'), (4, 'Black')], default=1, verbose_name='Color')),
                ('is_filtered', models.BooleanField(default=False, verbose_name='Is filtered?')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('image', models.ImageField(blank=True, max_length=400, null=True, upload_to=beers.utils.beer_image_upload_location, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Beer',
                'verbose_name_plural': 'Beers',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('beers', models.ManyToManyField(blank=True, related_name='special_ingredients', to='beers.Beer')),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='beers.Company'),
        ),
    ]
