# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='specialingredient',
            options={'verbose_name': 'Special ingredient', 'verbose_name_plural': 'Special ingredients'},
        ),
    ]
