# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20171116_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(default=1, null=True, verbose_name='Tax Number'),
            preserve_default=False,
        ),
    ]
