# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20171117_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(default=1, unique=True, verbose_name='Tax Number'),
            preserve_default=False,
        ),
    ]
